# .github/workflows/run.yml
name: IPTV Updater

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:

jobs:
  iptv-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: write
      actions: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp ratelimit

    - name: Create config structure
      run: |
        mkdir -p zubo output
        # 创建示例配置文件
        echo "湖南卫视,udp://225.1.1.1:5000" > zubo/湖南_电信.txt
        echo "192.168.1.0:8000,1" > config.txt

    - name: Run IPTV Scanner
      run: python hndxzb.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: iptv-lists
        path: |
          output/iptv_list.txt
          output/valid_ips.txt
        retention-days: 3

    - name: Commit results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add output/
        git commit -m "Auto-update IPTV lists - $(date +'%Y%m%d_%H%M%S')"
        git push
