name: HNDXZB

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp ratelimit

    - name: Create config
      run: |
        mkdir -p zubo
        echo "湖南_电信.txt示例内容" > zubo/湖南_电信.txt
        echo "192.168.1.1:8000,0" > config.txt

    - name: Run scanner
      run: python hndxzb.py

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: iptv-list
        path: output/
