# .github/workflows/iptv_updater.yml
name: IPTV List Updater

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次（UTC时间）
  workflow_dispatch:       # 允许手动触发

env:
  OUTPUT_DIR: output
  CONFIG_DIR: zubo

jobs:
  update-lists:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write  # 必须的提交权限

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # 使用GITHUB_TOKEN验证

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp ratelimit

    - name: Initialize directories
      run: |
        mkdir -p ${{ env.OUTPUT_DIR }} ${{ env.CONFIG_DIR }}
        # 安全创建示例文件（仅当不存在时）
        [ -f config.txt ] || echo "192.168.1.0:8000,1" > config.txt
        [ -f ${{ env.CONFIG_DIR }}/湖南_电信.txt ] || \
          echo "湖南卫视,udp://225.1.1.1:5000" > ${{ env.CONFIG_DIR }}/湖南_电信.txt

    - name: Run IPTV Scanner
      run: python main.py
      env:
        PYTHONUNBUFFERED: 1  # 实时输出日志

    - name: Commit updated lists
      run: |
        # 配置Git身份
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # 仅添加目标文件
        git add ${{ env.OUTPUT_DIR }}/iptv_list.txt

        # 生成带时区的提交信息
        COMMIT_TIME=$(date +"%Y-%m-%d %H:%M:%S (UTC)")
        COMMIT_MSG="🔄 Auto-update IPTV lists - $COMMIT_TIME"

        # 条件提交
        if git diff --cached --quiet; then
          echo "🟢 No changes to commit"
        else
          git commit -m "$COMMIT_MSG"
          git push origin HEAD:main
          echo "✅ Successfully pushed updates"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: iptv-lists
        path: |
          ${{ env.OUTPUT_DIR }}/*.txt
        retention-days: 3
